name: "OpenCPN (Ingress)"
version: "0.1.4"
slug: "opencpn_ingress"
description: "OpenCPN via KasmVNC, exposed only through Home Assistant ingress"

url: "https://github.com/moreau-it/home-assistant-add-ons"

arch:
  - aarch64
  - amd64
  - armv7

startup: services
init: false

# Ingress-only, no direct ports
ingress: true
ingress_port: 8099 # or 6080, but pick one and match EXTERNAL_PORT
ingress_entry: / # now that nginx handles root, / is fine

panel_icon: mdi:ship-wheel
panel_title: OpenCPN
panel_admin: false

homeassistant_api: false
hassio_role: default

privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH

options:
  vnc_password: "ChangeMe123"
  insecure_mode: true

schema:
  vnc_password: str
  insecure_mode: bool
